workflows:
  ios-build:
    name: Build iOS App Without Signing
    environment:
      xcode: latest
      node: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Build iOS app without signing
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                      -scheme app \
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath $HOME/build/App.xcarchive archive \
                      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
      - name: Export .ipa file
        script: |
          xcodebuild -exportArchive \
                      -archivePath $HOME/build/App.xcarchive \
                      -exportPath $HOME/build \
                      -exportOptionsPlist ios/App/ExportOptions.plist \
                      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
      - name: List schemes
        script: |
          xcodebuild -list -workspace ios/App/App.xcworkspace
    artifacts:
      - $HOME/build/*.ipa
