workflows:
  ios-build:
    name: Build iOS App Without Signing
    environment:
      xcode: latest
      node: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Ionic app
        script: |
          npm run build
      - name: Sync Capacitor plugins
        script: |
          npx cap sync ios
      - name: Build iOS app without signing
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                      -scheme App \
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath $HOME/build/App.xcarchive archive \
                      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
          - name: Export .ipa file
        script: |
          xcodebuild -exportArchive \
                      -archivePath $HOME/build/App.xcarchive \
                      -exportPath $HOME/build \
                      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""

    artifacts:
      - $HOME/build/*.ipa
