workflows:
  ios-build:
    name: Build iOS App Without Signing
    environment:
      xcode: latest
      node: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install CocoaPods
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios/App
          npm install
          pod install
      - name: List schemes
        script: |
          echo "Listing schemes available in the workspace..."
          xcodebuild -list -workspace ios/App/App.xcworkspace
      - name: Build iOS app without signing
        script: |
          echo "Building iOS app without signing..."
          xcodebuild -workspace ios/App/App.xcworkspace \
                      -scheme App \
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath $HOME/build/App.xcarchive archive \
                      xcodebuild -workspace ios/App/App.xcworkspace \
                      -scheme App \
                      -sdk iphoneos \
                      -configuration Release \
                      -destination "generic/platform=iOS" \
                      archive
                      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
      - name: Export .ipa file
        script: |
          echo "Exporting .ipa file..."
          xcodebuild -exportArchive \
                      -archivePath $HOME/build/App.xcarchive \
                      -exportPath $HOME/build \
                      -exportOptionsPlist ios/App/ExportOptions.plist \
                      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
    artifacts:
      - $HOME/build/*.ipa
